---
engines:
  duplication:
    enabled: false
  structure:
    enabled: false
  sonar-php:
    enabled: true
    config:
      minimum_severity: blocker
exclude_paths:
  - build/
  - fixtures/
  - gradle/
  - .gradle/
