---
engines:
  checks:
    enabled: true
    channel: beta
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- config/**/*
- tests/**/*
